### ISSUE TITLE
No continuous sound during Absorb, Protect, Rage and Speed

### ISSUE THREAD

**Issue by myacxy** [mvdevs/jk2mv#20] opened 2015-04-30 14:49 UTC
#### Steps to Reproduce
* Start any version
* Apply any skill rank of the force powers in question
* Activate any of the corresponding force powers

#### Actual Results
* Initial sound for triggering the force plays properly
* After activation of the force power there no sound cue despite the force still being activated

#### Expected Results
* Continuous sound during the entire duration of the force

Protect, Rage and Speed can be perceived visually but Absorb is only visible upon affection of a force and thus it is important for it be audible.

**Comment by ouned** [comment] 2015-04-30 15:23
Did you test on b3?
Seems to be a duplicate of https://github.com/mvdevs/jk2mv/issues/11 which is already fixed

**Comment by myacxy** [comment] 2015-04-30 16:21
Yes, I used 1.0b3. I tested again with jk2mv-v1.0b3-win-client-portable on a fresh installation and the problem persists. x86 and x64 behave in the same way.

**Comment by ouned** [comment] 2015-04-30 17:03
yeah 1.0b3 is not fixed. It is fixed in the code but we didn't make a new version out of it since.
You need to build the source yourself to get the fixed version.
@Daggolin fixed it in https://github.com/mvdevs/jk2mv/commit/b06857062e691b317960025c6ab174b67edad129

**Comment by Daggolin** [comment] 2015-05-01 00:08
The description fits issue #11, which was fixed in b068570.

**Closed by Daggolin** 2015-05-01 00:08 UTC
