### ISSUE TITLE
SDL input bug

### ISSUE THREAD

**Issue by Lomtvador** [mvdevs/jk2mv#92] opened 2017-04-26 11:52 UTC
Problem: (1) Volume down button treats as letter C and (2) volume up button treats as letter B.
I saw this bug on two different laptops and my PC from Windows XP through Windows 10 with english keymap enabled.
it's so annoying, because C is my crouch button and B is bacta.

Just look:
![shot0000](https://cloud.githubusercontent.com/assets/24492734/25432801/94199c32-2a8e-11e7-93ab-cae1b1f1bd39.jpg)
![c](https://cloud.githubusercontent.com/assets/24492734/25432984/68e6810a-2a8f-11e7-9718-706c9f703c9e.png)
![b](https://cloud.githubusercontent.com/assets/24492734/25433012/87f450cc-2a8f-11e7-9bdd-8fc0cf4918a7.png)

**Comment by ouned** [comment] 2017-04-26 18:23
i made a quick test and can confirm that
same happens for me on my notebook's FN + F key-combo but not on my "external" keyboard which has extra multimedia keys.

thanks for reporting

**Comment by ouned** [comment] 2017-05-22 07:53
the same doesn't happen on linux (gnome)
it doesnt seem to forward the keypress to the program at all and only gnome seems to progress it

**Comment by aufau** [comment] 2017-05-22 10:26
Does it happen on JK2MV 1.1.1? You can get a portable build from here: https://github.com/mvdevs/jk2mv/releases/tag/1.1.1

**Comment by Lomtvador** [comment] 2017-05-22 11:16
No, it doesn't. This bug came since version 1.2. Previous versions works fine.

**Comment by ouned** [comment] 2017-05-22 18:07
we use SDL on windows since 1.2

**Comment by aufau** [comment] 2017-05-24 15:48
Looks like a SDL2 issue since `e.key.keysym` already says 'C'. Would debug it if I had an environment to reproduce it. Unfortunately I deleted my win10 vm when it grew to almost 30gb :/

**Comment by ouned** [comment] 2017-05-31 10:15
So I found what the problem is
Everyone just does whatever they feel like: http://homepages.cwi.nl/~aeb/linux/kbd/scancodes-5.html

I'm not sure how linux and windows get it correct, they probably just a have a huge table of keyboard vendors and their keycodes and map it to their virtual keys.
But SDL uses raw keycode input and thus they'd have to do the same. I debugged SDL and it basically just passes what it gets from windows.

Probably SDL should only pass extended scancodes it knows about and ignore all others. (From what I can see there are a few well defined ones like the INSERT key)

In our case the input is:
```
e0 30 Volume increase (+)
e0 2e Volume decrease (-)
e0 20 Mute
```

**Comment by aufau** [comment] 2017-05-31 20:23
Great, I guess you should report it upstream and see how they want to handle it.
And for us maybe we could have a workaround either in jk2mv or in windows sdl static libraries (do you build them yourself?)?

**Comment by ouned** [comment] 2017-06-01 07:38
no i took the official ones so people can verify them as legit
I will look more into it in the next few days. I have some idea for an SDL fix but I need to test it at first

**Comment by ouned** [comment] 2017-06-03 07:36
So I created my patch and submitted it to the SDL bugtracker: https://bugzilla.libsdl.org/show_bug.cgi?id=3247

I will see if it's possible to create a workaround in the meantime because even if they accept the patch, a new SDL release probably takes ages.

**Comment by ouned** [comment] 2017-08-18 07:59
patch has been accepted and will be part of the next SDL2 release...

**Comment by ouned** [comment] 2017-10-25 11:16
confirmed for fixed.

**Closed by ouned** 2017-10-25 11:16 UTC
Labels: bug, confirmed
