### ISSUE TITLE
Option to not drop connection when cl.snap.serverTime < cl.oldFrameServerTime?

### ISSUE THREAD

**Issue by TomArrow** [mvdevs/jk2mv#146] opened 2021-10-28 04:00 UTC
With bad connection, sometimes ```cl.snap.serverTime < cl.oldFrameServerTime``` happens. As per now, this results in an error that forces a disconnect from the server, which is kinda frustrating.

I think it's here:
https://github.com/mvdevs/jk2mv/blob/1077d69d22376dd90f15920a97834637dd9c74bf/src/client/cl_cgame.cpp#L1571

Would be nice to add a settable option that allows to downgrade this error from an ERR_DROP to a PRINT_WARNING or something like that. Maybe it could even be auto-on? Is there a good reason to force a disconnect when this happens? In the case of a bad internet connection it doesn't seem like the desired behavior and since it's a clientside behavior, it seems it wouldn't interfere with the server either.

Just a thought.

**Comment by TomArrow** [comment] 2021-10-29 20:48
Okay I was finally able to reproduce it. I had no server with an active game to test on earlier, maybe that's why I failed to reproduce. Proof:

![2021-10-29 22_44_27-JK2MV](https://user-images.githubusercontent.com/6640421/139499886-e4a4ec68-1051-43d0-addb-aa7c7a6aa153.png)

**Comment by aufau** [comment] 2022-02-18 19:59
Fixed in 2eae94300395072598eb88c6f5b97ab2218beb4c
Sorry I forgot to add you as reported-by and tested-by in commit message and don't want to ammend now that I've pushed to the master.

**Closed by aufau** 2022-02-18 19:59 UTC

**Comment by entdark** [comment] 2022-02-18 21:19
Should that be changed in all q3-based engines?

P.S.: you can leave the reporter and the tester in the comment section under the commit.

**Comment by TomArrow** [comment] 2022-02-18 21:33
Maybe. The base Q3A repo by id software has a similar fix https://github.com/id-Software/Quake-III-Arena/blob/dbe4ddb10315479fc00086f08e25d968b4b43c49/code/qcommon/net_chan.c#L448

**Comment by entdark** [comment] 2022-02-18 22:29
Yeah but their "fix" was part of the original source code released in 2005 of version 1.32b.
I guess they worked close to Raven Software to share some fixes. But Raven Software were wuss to apply the fix according to the comments.
The very first commit of Jedi Outcast doesn't contain the fix. It was added in the second one: https://github.com/jedis/jedioutcast/commit/a8c260f9e47dbf490efa75eb2047fdfe6b7138f4#diff-8f9663e86e075916aed4ca92fe1824910e99c4595f24b5cca73895030567d300R451
So according to this the fix wasn't in Q3 source code before 2002-2003 (since Raven Software licensed it and used for themself and the very first commit doesn't have the "fix") and was applied in some earlier versions of Q3 before 1.32b. But we will never know which.

**Comment by aufau** [comment] 2022-02-19 17:25
As far as I understand this is how it should have always been. The way I found it is by looking where that function returns qtrue and checking if there is `chan->incomingSequence = sequence;` line there - debugged it and found the error/solution independently. Commented line there only confirmed my diagnosis.

If that code branch was reached, cg.snap was updated with new snapshot but incomingSequence wasn't. This made it possible to receive an earlier snapshot as next snapshot (due to packet reordering), parse it as new snapshot (because incomingSequence was not updated) and "downgrade" cg.snap to older snapshot which caused reported error.

**Comment by aufau** [comment] 2022-02-19 17:34
I'm gonna write down how it happened in case someone asks me about it N years later.

* Receive packet with full snapshot, serverTime 0 and sequence number 1 - netchan_t::incomingSequence is updated to 1, cl.snap is snapshot 1
* Receive 2 packets with fragmented snapshot, serverTime 100 and sequence number 3 - now netchan_t::incomingSequence is not updated and remains 1, but cl.snap is updated and cl.snap.serverTime == 100.
* Receive packet with full snapshot, serverTime 50 and sequence number 2 - this packet should be rejected but because netchan_t::incomingSequence < 2 it is not and parsed to cl.snap. Now cl.snap.serverTime == 50 and consequently cl.snap.serverTime went backwards.

To reproduce:
* add random latency to server -> client packets so that they may be reordered
* enable cl_nodelta, to force non-delta snapshots and bigger packets, and add a ton of bots - these two things are only so that some packets get too large and become fragmented in netchan
* wait. enable showpackets on client see received packets/sequence numbers/fragments
