### ISSUE TITLE
Bug in player list

### ISSUE THREAD

**Issue by Lomtvador** [mvdevs/jk2mv#98] opened 2018-01-23 17:19 UTC
Before JK2MV 1.4:
![shot0000](https://user-images.githubusercontent.com/24492734/35290171-6fdfe30e-007a-11e8-9312-dbc3821863a3.jpg)

JK2MV 1.4:
![shot0003](https://user-images.githubusercontent.com/24492734/35290208-8b3f8ee2-007a-11e8-8c52-cd7e7a840da5.jpg)
![shot0001](https://user-images.githubusercontent.com/24492734/35290210-8cb77640-007a-11e8-8234-26d380a931d3.jpg)
![shot0002](https://user-images.githubusercontent.com/24492734/35290212-8e8105b8-007a-11e8-9158-ed348b962ef3.jpg)

**Comment by ouned** [comment] 2018-01-23 17:51
I can confirm that.
Looks like it actually is an mvsdk bug

**Comment by aufau** [comment] 2018-01-23 19:17
Fixed in https://github.com/mvdevs/mvsdk/commit/559015f4032557808f1323f7a2df2d58c3a364b4
Thanks for reporting. This seems to be a buggy release, expect 1.4.1 in some time :P

**Closed by aufau** 2018-01-23 19:17 UTC
Labels: bug, confirmed, mvsdk
